"""v4

Revision ID: 81cde20c956e
Revises: 6d4bd1560ab6
Create Date: 2021-07-10 18:41:59.752651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81cde20c956e'
down_revision = '6d4bd1560ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('classification', sa.String(length=50), nullable=False))
    op.drop_column('products', '_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('_type', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('products', 'classification')
    # ### end Alembic commands ###
