"""v2

Revision ID: e186c0bd9520
Revises: 1e553ccc93c3
Create Date: 2021-07-09 09:38:37.111572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e186c0bd9520'
down_revision = '1e553ccc93c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('package_list', sa.String(length=100), nullable=False))
    op.add_column('products', sa.Column('rank', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'rank')
    op.drop_column('products', 'package_list')
    # ### end Alembic commands ###
